import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

    public static void main(String args[]) {
       // System.out.println(sum(1,2,3,4));
        System.out.println("multiply : " + multiply(4,6));

    }
    //join method implementation
     static String join(String delimiter,  String...stringsToJoin) {

        if(stringsToJoin == null )
        {
            return "";
        }
    return Arrays.stream(stringsToJoin)

            .reduce((identity,accumulator)->{
                if(delimiter==null ||delimiter.length()==0){
                    return identity+" "+accumulator;
                }else {return identity+delimiter+accumulator;}
            })
            .orElse("");

    }

    private static long multiply(final int startInclusive, final int endInclusive) {

        return IntStream.rangeClosed(startInclusive, endInclusive)
                .reduce((accumulator , currentNumber) -> {
                    System.out.println(accumulator);
                    System.out.println(currentNumber);
                    return accumulator * currentNumber;

                })
                .orElse(0);
    }

    private static long sum(final int...numbersToSum) {
        return Arrays.stream(numbersToSum)
                .reduce((left, right) -> left + right)
                .orElse(0);



    }
    static List<String> reverseString(final List<String> stringToReverse) {

        if (stringToReverse == null) {
            return Collections.emptyList();

        }
        return stringToReverse
                .stream()
                .filter(Objects::nonNull)
                .map(toReverseString)
                .collect(Collectors.toList());
    }

    private static Function<String, String> toReverseString= stringReversed -> new StringBuilder(stringReversed).reverse().toString();


    public static Map<String, Integer> wordCounts(String sentence) {


        Map<String, Integer> map = new HashMap<String, Integer>();
        map.put("babali" , 1);

        if(sentence == null  )
        {
            return Collections.emptyMap();
        }

            return map;




    }
}
