import java.util.Collections;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {


    public static List<String> reverseString(final List<String> stringToReverse) {

        return Collections.emptyList();

    }

}
