import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {


     static List<String> reverseString(final List<String> stringToReverse) {

        if(stringToReverse==null ){
            return Collections.emptyList();

        }
//        if(("foo").equals(stringToReverse.get(0))) {
//            return Collections.singletonList("oof");
//        }
         //return Collections.singletonList("bar");
         return stringToReverse
                 .stream()
                 .filter(Objects::nonNull)
         .map(stringReversed ->new StringBuilder(stringReversed).reverse().toString())
                 .collect(Collectors.toList());


    }




}
